services:
  db:
    image: mysql:8.0
    container_name: speakr_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: speakr_db
    ports:
      - '3306:3306'
